Add `safeCastTo()` #61
sindresorhus/ts-extras pull request #63
Opened 2024-08-14 16:07 UTC by Max10240

Closes #61

2024-08-15 15:11 UTC, Max10240 commented
Any suggestions about this PR? :)

2024-08-15 21:20 UTC, sindresorhus requested changes

2024-08-15 21:20 UTC, sindresorhus commented on source/safe-cast-to.ts
> +
It would be useful with a short explanation on how it's "safe" and better than just `as Partial<Foo>`.

2024-08-15 21:20 UTC, sindresorhus commented on source/safe-cast-to.ts
> +  b?: number;
Tab-indentation.

2024-08-15 21:20 UTC, sindresorhus commented on source/safe-cast-to.ts
> +interface Foo {
I prefer using `type` whenever possible.

2024-08-15 21:20 UTC, sindresorhus commented on source/safe-cast-to.ts
> +const bar = possibleUndefined || {};
```suggestion
const foo = possibleUndefined ?? safeCastTo<Partial<Foo>>({});
console.log(foo.a ?? '', foo.b ?? 0);

const bar = possibleUndefined ?? {};
```

2024-08-23 15:04 UTC, merged

2024-08-23 15:04 UTC, sindresorhus commented
Thanks :)