Add `asSubtype`
sindresorhus/ts-extras pull request #7
Opened 2021-10-27 07:28 UTC by alita-moore

I frequently run into edgecases that typescript has not addressed in their auto labeling of types. So I'm instead forced to redefine types or unnecessarily address supposedly nullable variables. This is a function to make overcoming these limitations easier.

2021-11-01 07:09 UTC, sindresorhus requested changes

2021-11-01 07:09 UTC, sindresorhus commented on source/as-subtype.ts
> +This is useful in cases where the typescript engine is unable to catch certain implicit assertions.
What cases? Can you describe succinctly and example situation where it might be needed?

2021-11-01 07:09 UTC, sindresorhus commented on source/as-subtype.ts
> +This is useful in cases where the typescript engine is unable to catch certain implicit assertions.
```suggestion
This is useful in cases where TypeScript is unable to catch certain implicit assertions.
```

2021-11-01 07:09 UTC, sindresorhus commented on source/as-subtype.ts
> +		console.log('this is to assuage the linter');
I think it's better to use an ESLint ignore comment.

2021-11-01 07:09 UTC, sindresorhus commented on test/as-subtype.ts
> +test('isDefined()', t => {
Typo

2021-11-01 07:09 UTC, sindresorhus commented on test/as-subtype.ts
> +	t.true(true);
```suggestion
	t.pass();
```

2021-11-01 07:13 UTC, sindresorhus commented on source/as-subtype.ts
> +```
```suggestion
```
import {asSubtype} from 'ts-extras';
```

2021-11-01 07:14 UTC, sindresorhus commented on source/as-subtype.ts
> +// This is particularly useful in async actions and
```suggestion
import {asSubtype} from 'ts-extras';

// This is particularly useful in async actions and
```

2021-11-01 07:14 UTC, sindresorhus commented on source/as-subtype.ts
> +export function asSubtype<T>(value: any): asserts value is T {
```suggestion
export function asSubtype<T>(value: unknown): asserts value is T {
```

2021-11-29 17:06 UTC, sindresorhus commented
@alita-moore Friendly bump :)

2021-12-01 06:05 UTC, alita-moore commented
Thanks! I'll address all comments on my PRs this weekend!

2021-12-01 07:05 UTC, sindresorhus commented
Great :)

Note that you now also need to add the types to the readme and add appropriate categories to the TS doc comments.

2022-01-23 10:44 UTC, sindresorhus commented
Bump :)

2022-03-16 08:49 UTC, closed without merging